/**
 * ALL existing website content for one-time CMS migration.
 * Sourced exactly from: site-config.ts, treatments/[slug]/page.tsx,
 * dental-guides/[slug]/page.tsx, patient-stories/page.tsx
 * DO NOT edit this file manually — it is the migration source of truth.
 */

export const MIGRATE_DOCTORS = [
  {
    slug: "dr-jeo-tom-charls",
    name: "Dr. Jeo Tom Charls",
    photo_url: "/images/dr-jeo-tom-charls.jpg",
    qualifications: "MDS",
    specialty: "Orthodontics and Dentofacial Orthopaedics",
    designation: "Principal Orthodontist",
    roles: ["Consultant Orthodontist", "Certified Invisalign Provider", "Certified Spark Aligner Provider"],
    visiting: false,
    registration_body: "Kerala State Dental Council",
    registration_number: "9451",
    registration_year: "2015",
    memberships: ["Indian Orthodontic Society", "Indian Dental Association"],
    education: [
      { degree: "BDS", institution: "Sri Balaji Dental College, Chennai", year: "2010" },
      { degree: "MDS — Orthodontics and Dentofacial Orthopaedics", institution: "Sri Balaji Dental College, Chennai", year: "2015" },
    ],
    professional_experience: [
      "Smile Architects, Pala",
      "Mar Sleeva Medicity, Palai",
      "Believer's Church Medical College & Hospital",
      "Raihan Institute of Medical Sciences",
      "V.V. Dental Clinic, Chennai",
    ],
    training: [
      "Certified Invisalign Provider",
      "Certified Spark Aligner Provider",
      "Lingual orthodontics training",
      "Lingual orthodontics CAD/CAM training",
      "ClearPath clear-aligner certification workshop",
      "TMJ considerations in functional orthodontics",
      "Miniscrews in orthodontics",
    ],
    areas_of_expertise: [
      "Conventional straight-wire appliances",
      "Damon / self-ligating brackets",
      "Ceramic brackets",
      "Lingual orthodontics / hidden braces",
      "Invisalign & Spark clear aligners",
      "Surgical orthodontics",
      "Orthognathic surgical planning",
      "Growth modification",
      "Fixed functional appliances",
      "Digital smile designing",
    ],
    bio: "Dr. Jeo Tom Charls is the principal orthodontist at Smile Architects, Pala. An MDS-qualified specialist in Orthodontics and Dentofacial Orthopaedics, he is a Certified Invisalign and Spark Aligner Provider with advanced training in lingual orthodontics and CAD/CAM bracket systems. His practice spans the full spectrum of orthodontic treatment — from conventional braces to completely hidden lingual systems and clear aligners.",
    seo_title: "Dr. Jeo Tom Charls | Orthodontist in Pala, Kottayam | Smile Architects",
    seo_description: "Dr. Jeo Tom Charls — MDS Orthodontics. Certified Invisalign & Spark Aligner Provider. Specialist in braces, lingual orthodontics and clear aligners at Smile Architects, Pala.",
    published: true,
    display_order: 1,
  },
  {
    slug: "dr-jom-t-kizhakkel",
    name: "Dr. Jom T. Kizhakkel",
    photo_url: "/images/team/dr-jom-t-kizhakkel.jpg",
    qualifications: "MDS",
    specialty: "Periodontics & Implantology",
    designation: "Periodontist & Implantologist",
    roles: ["Periodontist", "Implantologist"],
    visiting: false,
    registration_body: null,
    registration_number: null,
    registration_year: null,
    memberships: [],
    education: [{ degree: "MDS — Periodontics & Implantology", institution: "", year: "" }],
    professional_experience: ["Smile Architects, Pala"],
    training: [],
    areas_of_expertise: [
      "Periodontal treatment",
      "Scaling and root planing",
      "Gum surgery",
      "Dental implants",
      "Implant-supported restorations",
      "Bone grafting",
    ],
    bio: "Dr. Jom T. Kizhakkel is an MDS specialist in Periodontics and Implantology at Smile Architects, Pala. He manages gum disease treatment and dental implant placement, offering patients a complete solution for tooth loss and periodontal health.",
    seo_title: "Dr. Jom T. Kizhakkel | Periodontist & Implantologist in Pala | Smile Architects",
    seo_description: "Dr. Jom T. Kizhakkel — MDS Periodontics & Implantology. Specialist in dental implants and gum treatment at Smile Architects, Pala, Kottayam, Kerala.",
    published: true,
    display_order: 2,
  },
  {
    slug: "dr-kishore-george",
    name: "Dr. Kishore George",
    photo_url: "/images/team/dr-kishore-george.jpg",
    qualifications: "MDS",
    specialty: "Oral & Maxillofacial Surgery",
    designation: "Visiting Consultant — Oral & Maxillofacial Surgeon",
    roles: ["Visiting Consultant", "Oral & Maxillofacial Surgeon"],
    visiting: true,
    registration_body: null,
    registration_number: null,
    registration_year: null,
    memberships: [],
    education: [{ degree: "MDS — Oral & Maxillofacial Surgery", institution: "", year: "" }],
    professional_experience: [],
    training: [],
    areas_of_expertise: [
      "Complex tooth extractions",
      "Impacted wisdom tooth surgery",
      "Oral cyst and lesion removal",
      "Jaw surgery",
      "Pre-implant surgery",
      "Orthognathic surgery",
    ],
    bio: "Dr. Kishore George is a visiting consultant Oral & Maxillofacial Surgeon at Smile Architects, Pala. He manages complex surgical cases including impacted wisdom teeth, jaw surgery and pre-implant procedures.",
    seo_title: "Dr. Kishore George | Oral Surgeon — Visiting Consultant | Smile Architects Pala",
    seo_description: "Dr. Kishore George — MDS Oral & Maxillofacial Surgery. Visiting consultant at Smile Architects, Pala, Kottayam, Kerala.",
    published: true,
    display_order: 4,
  },
  {
    slug: "dr-renu-ann-mathew",
    name: "Dr. Renu Ann Mathew",
    photo_url: "/images/team/dr-renu-ann-mathew.jpg",
    qualifications: "MDS",
    specialty: "Paediatric & Preventive Dentistry",
    designation: "Visiting Consultant — Paediatric Dentist",
    roles: ["Visiting Consultant", "Paediatric Dentist"],
    visiting: true,
    registration_body: null,
    registration_number: null,
    registration_year: null,
    memberships: [],
    education: [{ degree: "MDS — Paediatric & Preventive Dentistry", institution: "", year: "" }],
    professional_experience: [],
    training: [],
    areas_of_expertise: [
      "Children's dental checkups",
      "Milk teeth treatment",
      "Dental sealants and fluoride",
      "Space maintainers",
      "Behavioural management",
      "Early orthodontic assessment",
    ],
    bio: "Dr. Renu Ann Mathew is a visiting consultant specialist in Paediatric & Preventive Dentistry at Smile Architects, Pala. She provides specialised dental care for children, focusing on prevention and creating a positive dental experience from an early age.",
    seo_title: "Dr. Renu Ann Mathew | Paediatric Dentist — Visiting Consultant | Smile Architects Pala",
    seo_description: "Dr. Renu Ann Mathew — MDS Paediatric & Preventive Dentistry. Visiting consultant at Smile Architects, Pala, Kottayam, Kerala.",
    published: true,
    display_order: 5,
  },
  {
    slug: "dr-akarsh-babu",
    name: "Dr. Akarsh Babu",
    photo_url: "/images/team/dr-akarsh-babu.jpg",
    qualifications: "MDS",
    specialty: "Prosthodontics",
    designation: "Visiting Consultant — Prosthodontist",
    roles: ["Visiting Consultant", "Prosthodontist"],
    visiting: true,
    registration_body: null,
    registration_number: null,
    registration_year: null,
    memberships: [],
    education: [{ degree: "MDS — Prosthodontics", institution: "", year: "" }],
    professional_experience: [],
    training: [],
    areas_of_expertise: [
      "Dental crowns and bridges",
      "Complete and partial dentures",
      "Implant-supported prostheses",
      "Full-mouth rehabilitation",
      "Smile makeovers",
      "Ceramic and zirconia restorations",
    ],
    bio: "Dr. Akarsh Babu is a visiting consultant Prosthodontist at Smile Architects, Pala. He specialises in complex restorative and prosthetic work including implant-supported prostheses, full-mouth rehabilitation and smile design.",
    seo_title: "Dr. Akarsh Babu | Prosthodontist — Visiting Consultant | Smile Architects Pala",
    seo_description: "Dr. Akarsh Babu — MDS Prosthodontics. Visiting consultant at Smile Architects, Pala, Kottayam, Kerala.",
    published: true,
    display_order: 6,
  },
];

export const MIGRATE_TREATMENTS = [
  {
    slug: "general-dentistry",
    title: "General Dentistry",
    short_description: "Preventive care, check-ups and routine dental treatment.",
    icon: "tooth",
    featured: true,
    published: true,
    display_order: 1,
    content: "General dentistry forms the foundation of good oral health. At Smile Architects, routine dental care includes check-ups, professional cleaning (scaling and polishing), fillings, tooth extractions and preventive advice. Regular visits allow early detection of problems before they become more complex or costly to treat.",
    benefits: [
      "Comprehensive dental examination and oral health assessment",
      "Scaling and polishing (professional cleaning)",
      "Tooth-coloured fillings (composite restorations)",
      "Tooth extraction, including simple surgical extractions",
      "Emergency dental care for pain or trauma",
      "Preventive advice: diet, brushing technique, fluoride",
      "Oral hygiene instruction tailored to your needs",
    ],
    seo_title: "General Dentistry in Pala, Kottayam | Smile Architects",
    seo_description: "General Dentistry at Smile Architects — Preventive care, check-ups and routine dental treatment. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "pediatric-dentistry",
    title: "Paediatric Dentistry",
    short_description: "Dental care tailored for children.",
    icon: "child",
    featured: true,
    published: true,
    display_order: 2,
    content: "Children's dental health requires a gentle, patient-centred approach. The team at Smile Architects is experienced in treating children across all ages — from first tooth check-ups through adolescence — in a calm, reassuring environment. Early dental visits help establish good habits and address issues like tooth decay, spacing or bite development before they worsen.",
    benefits: [
      "First dental visit check-ups for young children",
      "Preventive care: fluoride treatment and fissure sealants",
      "Fillings for primary (milk) and permanent teeth",
      "Space maintainers after early tooth loss",
      "Tooth extraction under local anaesthetic",
      "Guidance on thumb-sucking and oral habits",
      "Orthodontic assessment and growth monitoring",
    ],
    seo_title: "Paediatric Dentistry in Pala, Kottayam | Smile Architects",
    seo_description: "Paediatric Dentistry at Smile Architects — Dental care tailored for children. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "dental-implants",
    title: "Dental Implants",
    short_description: "A permanent solution for missing teeth.",
    icon: "implant",
    featured: true,
    published: true,
    display_order: 3,
    content: "Dental implants are the closest modern dentistry comes to a natural tooth replacement. A titanium post is surgically placed in the jawbone, integrates with the bone over time, and is then restored with a crown. The result is a fixed, stable tooth that looks, feels and functions like a natural tooth.",
    benefits: [
      "Single tooth implant placement and restoration",
      "Implant-supported bridges for multiple missing teeth",
      "Pre-implant assessment and treatment planning",
      "Digital X-ray and imaging for accurate implant placement",
      "Post-operative care and implant maintenance guidance",
      "Suitable for patients with healthy gums and adequate bone",
    ],
    seo_title: "Dental Implants in Pala, Kottayam | Smile Architects",
    seo_description: "Dental Implants at Smile Architects — A permanent solution for missing teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "cosmetic-dentistry",
    title: "Cosmetic Dentistry",
    short_description: "Improving the appearance of teeth and smile.",
    icon: "sparkle",
    featured: true,
    published: true,
    display_order: 4,
    content: "Cosmetic dentistry improves the appearance of your teeth, gums and smile. At Smile Architects, cosmetic treatments are carried out with attention to natural aesthetics — results should look like a better version of your own smile, not an artificial one. Dr. Jeo Tom Charls has additional training in aesthetic dentistry.",
    benefits: [
      "Teeth whitening (professional in-clinic and take-home)",
      "Tooth-coloured composite bonding",
      "Porcelain and composite veneers",
      "Gum contouring and aesthetic gum treatment",
      "Smile makeover planning",
      "Replacing old metal fillings with tooth-coloured restorations",
    ],
    seo_title: "Cosmetic Dentistry in Pala, Kottayam | Smile Architects",
    seo_description: "Cosmetic Dentistry at Smile Architects — Improving the appearance of teeth and smile. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "smile-design",
    title: "Smile Design",
    short_description: "Digital smile design for complete smile transformation.",
    icon: "smile",
    featured: true,
    published: true,
    display_order: 5,
    content: "Digital Smile Design (DSD) is a planning tool that allows you to preview your new smile before any treatment begins. Using photographs, digital design software and detailed clinical measurements, your desired outcome is visualised and agreed upon, then used to guide every step of the actual treatment. It brings together orthodontics, restorative and cosmetic dentistry into a single, coordinated plan.",
    benefits: [
      "Photographic analysis and digital smile simulation",
      "Combined treatment planning across specialties",
      "Mock-up trials before permanent treatment",
      "Coordination of orthodontics, veneers and restorations",
      "Smile design for weddings, special occasions and career goals",
      "Detailed digital treatment preview and discussion",
    ],
    seo_title: "Smile Design in Pala, Kottayam | Smile Architects",
    seo_description: "Smile Design at Smile Architects — Digital smile design for complete smile transformation. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "root-canal-treatment",
    title: "Root Canal Treatment",
    short_description: "Saving infected or damaged teeth.",
    icon: "canal",
    featured: true,
    published: true,
    display_order: 6,
    content: "Root canal treatment (endodontic treatment) relieves pain and saves teeth that would otherwise need to be extracted. When the nerve or pulp inside a tooth becomes infected or irreversibly inflamed — typically due to deep decay, a crack or trauma — the infected tissue is removed, the root canals are cleaned and shaped, and the tooth is sealed and restored. Modern root canal treatment is performed under local anaesthetic and is generally no more uncomfortable than a routine filling.",
    benefits: [
      "Single and multi-visit root canal procedures",
      "Treatment of infected, painful or abscessed teeth",
      "Digital X-ray for accurate canal length measurement",
      "Post and core placement where required",
      "Crown placement to restore the treated tooth",
      "Re-treatment of previously root-filled teeth",
    ],
    seo_title: "Root Canal Treatment in Pala, Kottayam | Smile Architects",
    seo_description: "Root Canal Treatment at Smile Architects — Saving infected or damaged teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "restorative-dentistry",
    title: "Restorative Dentistry",
    short_description: "Restoring teeth damaged by decay or injury.",
    icon: "restore",
    featured: false,
    published: true,
    display_order: 7,
    content: "Restorative dentistry focuses on repairing damaged, decayed or missing teeth. At Smile Architects the goal is to restore both function and aesthetics — fillings, inlays, onlays, crowns and bridges are matched to natural tooth colour wherever possible.",
    benefits: [
      "Direct composite fillings (tooth-coloured)",
      "Amalgam replacement with composite or ceramic restorations",
      "Inlays and onlays for large cavities",
      "Dental crowns for heavily damaged or root-treated teeth",
      "Bridges to replace missing teeth",
      "Post and core build-ups",
    ],
    seo_title: "Restorative Dentistry in Pala, Kottayam | Smile Architects",
    seo_description: "Restorative Dentistry at Smile Architects — Restoring teeth damaged by decay or injury. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "oral-surgery",
    title: "Oral & Maxillofacial Surgery",
    short_description: "Surgical care for the mouth, jaws and related structures.",
    icon: "surgery",
    featured: false,
    published: true,
    display_order: 8,
    content: "Oral and maxillofacial surgery at Smile Architects covers the surgical procedures needed for teeth, jaws and surrounding structures — from routine extractions to minor surgical procedures. Complex surgical needs are assessed and referred appropriately.",
    benefits: [
      "Simple and surgical tooth extractions",
      "Impacted wisdom tooth assessment and extraction",
      "Minor cyst and lesion removal",
      "Frenectomy (frenum removal)",
      "Alveoloplasty and ridge preparation for dentures",
      "Pre-implant surgical procedures",
    ],
    seo_title: "Oral & Maxillofacial Surgery in Pala, Kottayam | Smile Architects",
    seo_description: "Oral & Maxillofacial Surgery at Smile Architects — Surgical care for the mouth, jaws and related structures. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "orthodontics",
    title: "Orthodontics",
    short_description: "Correcting misaligned teeth and jaw relationships.",
    icon: "braces",
    featured: true,
    published: true,
    display_order: 9,
    content: "Orthodontic treatment corrects misaligned teeth and jaws to improve both function and appearance. At Smile Architects, Dr. Jeo Tom Charls — MDS Orthodontics and Dentofacial Orthopaedics — provides a full range of orthodontic treatment for children, adolescents and adults. A detailed orthodontic assessment determines the most appropriate appliance and treatment duration.",
    benefits: [
      "Comprehensive orthodontic assessment including X-rays and study models",
      "Metal and ceramic fixed appliances (braces)",
      "Damon / self-ligating brace systems",
      "Lingual braces (hidden braces on the inner tooth surface)",
      "Clear aligner treatment",
      "Growth modification and functional appliances for children",
      "Surgical orthodontics in coordination with oral surgeons",
      "Retainers and post-treatment monitoring",
    ],
    seo_title: "Orthodontics in Pala, Kottayam | Smile Architects",
    seo_description: "Orthodontics at Smile Architects — Correcting misaligned teeth and jaw relationships. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "braces",
    title: "Dental Braces",
    short_description: "Metal, ceramic and self-ligating brace systems.",
    icon: "braces",
    featured: true,
    published: true,
    display_order: 10,
    content: "Dental braces use a system of brackets, wires and elastic ties to gradually reposition teeth. Smile Architects offers metal braces, ceramic (tooth-coloured) braces and self-ligating systems such as Damon brackets. The choice of appliance depends on your clinical needs, aesthetic preferences and budget. Treatment is led by Dr. Jeo Tom Charls, MDS Orthodontics.",
    benefits: [
      "Metal braces — durable and cost-effective",
      "Ceramic braces — tooth-coloured brackets for a discreet look",
      "Damon / self-ligating brackets — lower friction for potentially shorter treatment",
      "Regular adjustment appointments every 4–8 weeks",
      "Digital X-rays and progress records throughout treatment",
      "Retainers provided at end of treatment",
    ],
    seo_title: "Dental Braces in Pala, Kottayam | Smile Architects",
    seo_description: "Dental Braces at Smile Architects — Metal, ceramic and self-ligating brace systems. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "clear-aligners",
    title: "Clear Aligners",
    short_description: "Transparent removable aligners for discreet treatment.",
    icon: "aligner",
    featured: true,
    published: true,
    display_order: 11,
    content: "Clear aligners are a series of transparent, removable trays that gradually move teeth to the desired position. They are virtually invisible when worn, can be removed for eating and cleaning, and are a popular choice for adults and older teenagers. Dr. Jeo Tom Charls has completed ClearPath aligner certification training.",
    benefits: [
      "Custom-fabricated clear aligner series",
      "Suitable for mild to moderate crowding, spacing and bite issues",
      "Removable for eating, drinking and oral hygiene",
      "Shorter chair-time compared to fixed appliances",
      "ClearPath certified treatment",
      "Digital treatment planning with predicted tooth movements",
      "Retainers on completion",
    ],
    seo_title: "Clear Aligners in Pala, Kottayam | Smile Architects",
    seo_description: "Clear Aligners at Smile Architects — Transparent removable aligners for discreet treatment. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "lingual-braces",
    title: "Lingual Braces",
    short_description: "Hidden braces fitted to the inner surface of teeth.",
    icon: "lingual",
    featured: true,
    published: true,
    display_order: 12,
    content: "Lingual braces are fixed orthodontic appliances bonded to the inner (tongue-side) surface of the teeth. When you smile, they are completely hidden. Dr. Jeo Tom Charls has completed dedicated lingual orthodontics training and CAD/CAM lingual bracket training, allowing him to offer this highly specialised treatment at Smile Architects.",
    benefits: [
      "Brackets bonded to the inner surface of teeth — invisible from the front",
      "Suitable for the same range of cases as conventional braces",
      "CAD/CAM customised lingual bracket systems",
      "Dedicated training in lingual orthodontic techniques",
      "Regular monitoring appointments throughout treatment",
      "Retainers provided on completion",
    ],
    seo_title: "Lingual Braces in Pala, Kottayam | Smile Architects",
    seo_description: "Lingual Braces at Smile Architects — Hidden braces fitted to the inner surface of teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "periodontal-treatment",
    title: "Periodontal Treatment",
    short_description: "Treatment for gum disease and supporting structures.",
    icon: "gum",
    featured: false,
    published: true,
    display_order: 13,
    content: "Periodontal (gum) disease is one of the most common causes of tooth loss in adults, and can also affect general health. At Smile Architects, gum health is assessed at every routine visit. Scaling and root planing, oral hygiene reinforcement and targeted periodontal treatment are provided where indicated.",
    benefits: [
      "Periodontal assessment and probing",
      "Professional scaling and root planing (deep cleaning)",
      "Oral hygiene instruction and technique review",
      "Monitoring and maintenance programmes",
      "Referral for advanced surgical periodontal treatment where required",
    ],
    seo_title: "Periodontal Treatment in Pala, Kottayam | Smile Architects",
    seo_description: "Periodontal Treatment at Smile Architects — Treatment for gum disease and supporting structures. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "prosthodontics",
    title: "Prosthodontics",
    short_description: "Replacing and restoring missing or damaged teeth.",
    icon: "prosthetic",
    featured: false,
    published: true,
    display_order: 14,
    content: "Prosthodontics focuses on restoring and replacing teeth using dental prostheses. At Smile Architects this includes crowns, bridges, dentures and implant-supported restorations. The aim is to restore comfortable function, natural aesthetics and confidence.",
    benefits: [
      "Dental crowns (ceramic, PFM, zirconia)",
      "Fixed dental bridges",
      "Complete and partial dentures",
      "Implant-supported crowns and bridges",
      "Implant-supported overdentures",
      "Temporary and immediate prostheses",
    ],
    seo_title: "Prosthodontics in Pala, Kottayam | Smile Architects",
    seo_description: "Prosthodontics at Smile Architects — Replacing and restoring missing or damaged teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "crowns",
    title: "Dental Crowns",
    short_description: "Caps that restore and protect damaged teeth.",
    icon: "crown",
    featured: false,
    published: true,
    display_order: 15,
    content: "A dental crown is a cap placed over a damaged, weakened or root-treated tooth to restore its shape, strength and appearance. Modern crowns are made from tooth-coloured materials — zirconia or all-ceramic — that blend naturally with surrounding teeth.",
    benefits: [
      "All-ceramic and zirconia crowns for natural aesthetics",
      "Porcelain-fused-to-metal (PFM) crowns",
      "Crowns for root canal treated teeth",
      "Crowns to restore fractured or heavily filled teeth",
      "Implant crowns",
      "Temporary crowns during fabrication",
    ],
    seo_title: "Dental Crowns in Pala, Kottayam | Smile Architects",
    seo_description: "Dental Crowns at Smile Architects — Caps that restore and protect damaged teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "bridges",
    title: "Dental Bridges",
    short_description: "Fixed replacement for one or more missing teeth.",
    icon: "bridge",
    featured: false,
    published: true,
    display_order: 16,
    content: "A dental bridge replaces one or more missing teeth by using adjacent teeth (or implants) as supports. A bridge is fixed — it is permanently cemented and does not need to be removed. It restores chewing function, prevents remaining teeth from drifting and maintains facial structure.",
    benefits: [
      "Three-unit and multi-unit fixed bridges",
      "All-ceramic and PFM bridge options",
      "Implant-supported bridges (no preparation of adjacent teeth)",
      "Maryland bonded bridges for conservative treatment",
      "Temporary bridges during fabrication",
    ],
    seo_title: "Dental Bridges in Pala, Kottayam | Smile Architects",
    seo_description: "Dental Bridges at Smile Architects — Fixed replacement for one or more missing teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "dentures",
    title: "Dentures",
    short_description: "Removable replacements for missing teeth.",
    icon: "denture",
    featured: false,
    published: true,
    display_order: 17,
    content: "Dentures are removable replacements for missing teeth and surrounding gum tissue. At Smile Architects, complete dentures (for patients missing all teeth in an arch) and partial dentures (for patients with some remaining natural teeth) are provided. Implant-supported overdentures offer a more stable alternative.",
    benefits: [
      "Complete acrylic dentures for full tooth loss",
      "Partial dentures — acrylic and metal-based (cobalt chrome)",
      "Immediate dentures placed the same day as extractions",
      "Denture relines and repairs",
      "Implant-supported overdentures for greater stability",
    ],
    seo_title: "Dentures in Pala, Kottayam | Smile Architects",
    seo_description: "Dentures at Smile Architects — Removable replacements for missing teeth. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
  {
    slug: "veneers",
    title: "Dental Veneers",
    short_description: "Thin porcelain or composite shells for smile improvement.",
    icon: "veneer",
    featured: false,
    published: true,
    display_order: 18,
    content: "Dental veneers are thin shells of porcelain or composite resin bonded to the front surface of teeth to improve their colour, shape, size or length. Porcelain veneers are highly lifelike and stain-resistant. Composite veneers can often be completed in a single visit with minimal tooth preparation.",
    benefits: [
      "Porcelain (ceramic) veneers — lab-fabricated, highly aesthetic",
      "Direct composite veneers — single-visit, minimal preparation",
      "Suitable for discolouration, chips, gaps and minor misalignment",
      "Digital smile design mock-up before any tooth preparation",
      "No or minimal tooth reduction for direct composite veneers",
    ],
    seo_title: "Dental Veneers in Pala, Kottayam | Smile Architects",
    seo_description: "Dental Veneers at Smile Architects — Thin porcelain or composite shells for smile improvement. Multispeciality dental clinic in Pala, Kottayam District, Kerala. Call +91 9446 999 333.",
  },
];

export const MIGRATE_GUIDES = [
  {
    slug: "braces-what-to-expect",
    title: "What to expect from braces treatment",
    excerpt: "From your first orthodontic assessment to retainers — a clear overview of the braces treatment journey at Smile Architects.",
    category: "Orthodontics",
    author: "Smile Architects",
    status: "published",
    seo_title: "What to expect from braces treatment | Smile Architects Pala",
    seo_description: "A clear guide to braces treatment at Smile Architects — from your first orthodontic assessment through to retainers and aftercare.",
    content: `## Initial orthodontic assessment

The first step is a detailed orthodontic consultation. Dr. Jeo Tom Charls will examine your teeth, take digital X-rays and, where required, orthodontic study models. He will assess your bite, jaw relationship, degree of crowding or spacing, and discuss the treatment options available to you — including fixed braces, lingual braces and clear aligners.

## Treatment planning

Once the assessment is complete, a personalised treatment plan is discussed. This outlines the type of appliance recommended, the estimated treatment duration, and the number and frequency of adjustment appointments. For some cases, extractions or other preparatory work may be needed first.

## Fitting the braces

The brace-fitting appointment typically takes 45–90 minutes. The teeth are cleaned and prepared, brackets are bonded to the tooth surfaces using dental adhesive, and the archwire is threaded through and secured. You may experience some soreness and sensitivity for a few days after fitting as teeth begin to move — this is normal and usually settles with over-the-counter pain relief.

## Adjustment appointments

Throughout treatment you will attend regular appointments, typically every 4–8 weeks, where the wire and elastic ties are changed to maintain the force moving your teeth. These appointments usually take 20–30 minutes. Progress X-rays may be taken at intervals.

## Oral hygiene with braces

Keeping your teeth and braces clean is critical during treatment. Food traps more easily around brackets and wires, increasing the risk of decay and white-spot lesions. Brushing after every meal, using interdental brushes and a fluoride mouthwash are all recommended. The team will provide detailed oral hygiene guidance at your fitting appointment.

## Retainers and after treatment

Once the braces are removed, retainers are fitted to hold the teeth in their new positions. Retainers are usually worn full-time for the first few months and then at night long-term. Teeth have a natural tendency to drift back, so consistent retainer wear is essential to maintain your result.`,
  },
  {
    slug: "clear-aligners-vs-braces",
    title: "Clear aligners vs braces: which is right for you?",
    excerpt: "A balanced comparison of clear aligner systems and fixed braces — covering aesthetics, cost, comfort and clinical suitability.",
    category: "Orthodontics",
    author: "Smile Architects",
    status: "published",
    seo_title: "Clear aligners vs braces: which is right for you? | Smile Architects Pala",
    seo_description: "A balanced comparison of clear aligner systems and fixed braces — covering aesthetics, comfort, cost and which cases each is best suited to.",
    content: `## How they work

Both fixed braces and clear aligners move teeth through sustained, controlled pressure — but in different ways. Braces use bonded brackets and an archwire that is progressively tightened at each appointment. Clear aligners use a series of custom-fitted transparent trays, each worn for one to two weeks before progressing to the next.

## Appearance

Clear aligners are virtually invisible when worn, which is their main aesthetic advantage. Ceramic (tooth-coloured) braces are more discreet than metal braces but still visible at close range. Lingual braces are bonded to the inner tooth surface and are completely hidden from the front — for patients who want fixed appliances without any visible hardware.

## Clinical suitability

Fixed braces can address a broader range of orthodontic problems — including complex bite corrections, rotations and significant crowding — more predictably than aligners. Clear aligners work well for mild to moderate cases and are particularly popular among adults with spacing or mild crowding. Not all cases are suitable for aligners; your orthodontist will advise based on your clinical needs.

## Compliance and lifestyle

Clear aligners must be worn 20–22 hours a day to be effective. They are removed for eating and cleaning, which many patients find convenient — but the outcome depends heavily on consistent wear. Fixed braces are non-removable, so compliance is built in.

## Comfort

Most patients experience some discomfort during the first few days after new trays or a brace adjustment as teeth begin to move. Aligners generally produce fewer episodes of sharp discomfort compared to metal braces. Lingual braces can initially affect speech and tongue comfort more than labial (outer) appliances.

## Treatment duration

Both systems typically take 12–24 months for moderate cases, though simple cases can be shorter. Complex cases are more predictably managed with fixed braces. Your orthodontist will provide an estimated treatment duration after examining your case.

## Making the decision

The best appliance is the one that is clinically appropriate for your teeth and fits your lifestyle. At Smile Architects, Dr. Jeo Tom Charls will assess your case and present the options available to you — without pushing one system over another. A full range of fixed, lingual and clear aligner options are available.`,
  },
  {
    slug: "lingual-braces-guide",
    title: "Lingual braces (hidden braces): a patient guide",
    excerpt: "How lingual braces work, what to expect during treatment, and why some patients prefer them over conventional or clear aligner options.",
    category: "Orthodontics",
    author: "Smile Architects",
    status: "published",
    seo_title: "Lingual Braces (Hidden Braces): A Patient Guide | Smile Architects Pala",
    seo_description: "How lingual braces work, what the treatment experience is like, and who they are suitable for — a patient guide from Smile Architects, Pala.",
    content: `## What are lingual braces?

Lingual braces are orthodontic brackets bonded to the inner (tongue-side, or lingual) surfaces of the teeth. Because they are hidden behind the teeth, they are completely invisible from the front and sides — even when you open your mouth. They are the only truly hidden fixed orthodontic appliance.

## How they work

Lingual brackets work on the same mechanical principle as conventional braces — brackets bonded to the teeth, an archwire threaded through, and progressive force moving the teeth to the desired position. The difference is only in where they are placed.

## Specialist training

Lingual orthodontics requires additional clinical training — the anatomy and working conditions are significantly different from labial (outer) braces. Dr. Jeo Tom Charls has completed dedicated lingual orthodontics training as well as CAD/CAM lingual bracket training, qualifying him to provide this treatment at Smile Architects.

## Speech adaptation

Most patients experience some change in speech — particularly the 's' and 't' sounds — for the first one to two weeks of treatment. This is because the tongue needs to adapt to the presence of brackets on the inner tooth surfaces. The vast majority of patients adapt fully within a few weeks.

## Oral hygiene

Cleaning lingual braces requires careful technique. An angled toothbrush, interdental brushes and floss threaders or a water flosser are recommended. The team at Smile Architects will provide detailed oral hygiene instruction at your fitting appointment.

## Who is a candidate?

Lingual braces can treat most of the same cases as conventional braces. They are particularly popular with adults in professional or public-facing roles who want effective fixed treatment without visible hardware. A full clinical assessment by Dr. Jeo Tom Charls will determine if lingual braces are appropriate for your case.`,
  },
  {
    slug: "dental-implants-guide",
    title: "Dental implants: your questions answered",
    excerpt: "Everything you need to know before considering a dental implant — the procedure, healing time, costs and long-term care.",
    category: "Implants",
    author: "Smile Architects",
    status: "published",
    seo_title: "Dental Implants: Your Questions Answered | Smile Architects Pala",
    seo_description: "A comprehensive patient guide to dental implants at Smile Architects, Pala — covering the procedure, healing time, candidacy, costs and long-term care.",
    content: `## What is a dental implant?

A dental implant is a small titanium post that is surgically placed into the jawbone to act as an artificial tooth root. Once the implant has bonded with the bone (a process called osseointegration, which takes several months), a custom crown, bridge or denture is attached to it. The result is a fixed, stable restoration that looks and functions like a natural tooth.

## Am I a suitable candidate?

Good candidates for implants have healthy gums, sufficient jawbone volume to support the implant, and no uncontrolled systemic conditions that would impair healing. Smoking significantly increases the risk of implant failure. If bone volume is insufficient, bone grafting may be possible before implant placement. A thorough assessment at Smile Architects will determine your suitability.

## The procedure step by step

The process typically involves: (1) Initial assessment and treatment planning, including X-rays or cone-beam CT imaging. (2) Surgical placement of the implant post under local anaesthetic — most patients find this no more uncomfortable than a tooth extraction. (3) A healing period of 3–6 months for the implant to integrate with the bone. (4) Placement of the abutment (connector). (5) Fitting of the permanent crown or restoration.

## Healing and aftercare

Some swelling and soreness in the days after implant surgery is normal. Over-the-counter pain relief is usually sufficient. Soft food is advised for the first week. Strict oral hygiene around the implant site is important during healing, and the team will provide specific aftercare guidance.

## How long do implants last?

With proper care — regular brushing, flossing, and professional dental check-ups — dental implants can last many decades. Studies show high long-term survival rates. The crown on top may need replacing after 10–15 years due to normal wear.

## Costs

Implant costs vary depending on the number of implants, the type of restoration needed, and whether any preparatory procedures are required. At Smile Architects, a detailed treatment plan with costs will be provided at your consultation before any commitment is required.`,
  },
  {
    slug: "root-canal-myths",
    title: "Root canal treatment: separating fact from fiction",
    excerpt: "Root canal treatment has an unfair reputation. Here we address the most common concerns and explain what modern endodontic treatment actually involves.",
    category: "General Dentistry",
    author: "Smile Architects",
    status: "published",
    seo_title: "Root Canal Treatment: Separating Fact from Fiction | Smile Architects Pala",
    seo_description: "Root canal treatment has an unfair reputation. We address the most common patient concerns and explain what modern endodontic treatment actually involves.",
    content: `## "Root canal treatment is very painful"

This is the most common misconception. Root canal treatment is performed under local anaesthetic, so the procedure itself should be no more painful than a filling. Any pre-existing pain from the infection is what patients often associate with the treatment — not the treatment itself. Mild soreness after the procedure is normal and typically settles within a few days.

## "It is better to just extract the tooth"

Preserving a natural tooth is almost always preferable to extraction if it can be saved. Natural teeth function better than any replacement, and losing a tooth has consequences: the remaining teeth may shift, chewing efficiency may be reduced, and replacing the missing tooth with a bridge or implant is more complex and expensive than treating it.

## "Root canal treatment takes many visits"

Many root canal treatments can be completed in one or two visits. More complex cases — involving multiple root canals or severe infection — may require additional appointments. Your dentist will give you a realistic estimate after examining your tooth.

## "The tooth will need extracting eventually anyway"

A well-performed root canal treatment, followed by an appropriate restoration (usually a crown), can allow a tooth to function for many years or even a lifetime. Regular dental check-ups allow the treated tooth to be monitored.

## What to expect

After local anaesthetic is administered, the dentist removes the infected pulp tissue from inside the tooth, cleans and shapes the root canals, and seals them. The tooth is then restored — typically with a post and core build-up followed by a crown. You can drive yourself home after treatment.`,
  },
  {
    slug: "childrens-dental-health",
    title: "Children's dental health: a parent's guide",
    excerpt: "When to bring your child to the dentist, how to manage milk teeth, preventing decay, and what to watch for as permanent teeth emerge.",
    category: "Paediatric Dentistry",
    author: "Smile Architects",
    status: "published",
    seo_title: "Children's Dental Health: A Parent's Guide | Smile Architects Pala",
    seo_description: "When to take your child to the dentist, how to manage milk teeth and decay, and what to watch for as permanent teeth come through — a guide from Smile Architects.",
    content: `## When should my child first visit the dentist?

The first dental visit should happen around the time the first tooth appears — typically at 6–12 months. Early visits help children become familiar with the dental environment, allow early detection of any issues, and give parents guidance on feeding, teething and oral hygiene.

## Milk teeth matter

Primary (milk) teeth are not 'just temporary'. They maintain the space for permanent teeth, help with speech development, and allow normal chewing. Decay in milk teeth can be painful, can spread, and can affect the developing permanent teeth beneath. Treating and preserving milk teeth is important.

## Preventing tooth decay in children

Limit sugary snacks and drinks to mealtimes. Brush teeth twice daily with a fluoride toothpaste — a smear for children under 3, a pea-sized amount from age 3. Children need help and supervision with brushing until they are around 7–8 years old. Fissure sealants on permanent back teeth can significantly reduce the risk of decay.

## Orthodontic assessment

From around age 7–8, the mix of milk and permanent teeth allows an orthodontist to identify emerging bite problems. Early assessment does not always mean early treatment — but it allows the clinician to monitor development and intervene at the optimal time if needed.

## Dental anxiety in children

Children who have positive early dental experiences are less likely to develop dental anxiety later in life. The Smile Architects team takes time to explain procedures in child-friendly terms, build rapport, and ensure visits are as calm and comfortable as possible.`,
  },
  {
    slug: "smile-design-guide",
    title: "Smile design: what is it and who is it for?",
    excerpt: "Digital Smile Design allows you to preview your new smile before treatment. Learn how the process works and what treatments it can include.",
    category: "Cosmetic Dentistry",
    author: "Smile Architects",
    status: "published",
    seo_title: "Smile Design: What Is It and Who Is It For? | Smile Architects Pala",
    seo_description: "A guide to Digital Smile Design at Smile Architects — how the process works, what treatments it can include, and who it is suitable for.",
    content: `## What is Digital Smile Design?

Digital Smile Design (DSD) is a clinical and communication tool that uses photographs, measurements and digital design software to create a preview of your new smile. The final design is agreed upon with you before any treatment begins — so there are no surprises.

## Who is it for?

Smile design is suitable for anyone who wants to improve the appearance of their smile in a comprehensive, coordinated way. It is particularly valuable for patients considering multiple treatments — for example, combining orthodontics with veneers or teeth whitening — or for those who want to see a realistic preview before committing.

## What treatments can be included?

A smile design plan can incorporate orthodontics (braces or aligners) to correct alignment, tooth-coloured restorations or veneers to improve shape and colour, teeth whitening, gum contouring, dental implants for missing teeth, and crown or bridge work. The combination is tailored to your goals and clinical needs.

## The process

The smile design process starts with a detailed consultation, including clinical examination and high-quality photographs. Dr. Jeo Tom Charls creates a digital design that maps tooth proportions, midline, gum line and overall aesthetics. A wax mock-up or digital preview is shared with you. Once agreed, treatment begins — with the design serving as a blueprint throughout.

## Is it worth it?

For patients planning significant smile changes, a smile design consultation saves time and prevents misaligned expectations. Seeing a realistic preview before treatment begins gives confidence, helps clarify goals, and results in a more predictable outcome.`,
  },
  {
    slug: "oral-hygiene-tips",
    title: "Oral hygiene: the basics that make a real difference",
    excerpt: "Simple, evidence-based guidance on brushing, flossing, diet and regular check-ups — the everyday habits that protect teeth and gums long-term.",
    category: "General Dentistry",
    author: "Smile Architects",
    status: "published",
    seo_title: "Oral Hygiene: The Basics That Make a Real Difference | Smile Architects Pala",
    seo_description: "Simple, evidence-based oral hygiene guidance from Smile Architects — brushing technique, flossing, diet and why regular dental check-ups matter.",
    content: `## Brushing

Brush for two minutes, twice a day — last thing at night and at one other time. Use a fluoride toothpaste (at least 1350–1500ppm fluoride for adults). A soft to medium manual or electric toothbrush works well; electric brushes may be more effective for those with limited dexterity. Do not rinse with water immediately after brushing — spit but do not rinse, to allow the fluoride to remain in contact with teeth.

## Cleaning between teeth

Brushing alone does not clean between teeth, where most decay and gum disease starts. Interdental brushes (small bottle-brush-like tools sized for your gaps) are the most effective option for most people. Dental floss is the alternative for very tight contacts. Aim to clean between all teeth once a day.

## Diet and frequency

It is not just how much sugar you consume — it is how often. Every time you eat or drink something sugary or acidic, your teeth are under attack for up to an hour. Limiting sugar and acid to mealtimes gives teeth recovery time. Drink water or plain milk between meals. Chewing sugar-free gum after meals can help neutralise acid.

## Regular dental check-ups

Routine dental check-ups allow early detection of decay, gum disease and other issues before they become more complex. How often you need to attend depends on your individual risk — your dentist will advise. Professional cleaning (scaling and polishing) removes calculus (hardened plaque) that cannot be removed by brushing alone.

## Fluoride

Fluoride strengthens enamel and makes teeth more resistant to decay. It is present in most toothpastes at effective concentrations. Additional fluoride — in the form of a mouthwash or higher-concentration toothpaste — may be recommended for patients at higher risk of decay.`,
  },
];

export const MIGRATE_PATIENT_STORIES = [
  {
    title: "Riya M. — Orthodontics & Braces",
    story: "Ceramic braces treatment over 14 months at Smile Architects, Pala.",
    testimonial: "I had been putting off braces for years. Dr. Jeo took the time to explain every option — braces, aligners, lingual braces — without any pressure. I went with ceramic braces and the result after 14 months was beyond what I expected.",
    published: true,
    featured: true,
    display_order: 1,
  },
  {
    title: "Arun K. — Dental Implants",
    story: "Dental implant for tooth lost in an accident, placed at Smile Architects, Pala.",
    testimonial: "I lost a tooth in an accident and was really anxious about implant surgery. The team were incredibly calm and professional throughout. The implant has been perfect for over a year now — I forget it's not my natural tooth.",
    published: true,
    featured: true,
    display_order: 2,
  },
  {
    title: "Shalini J. — Lingual Braces",
    story: "Lingual (hidden) braces treatment for a client-facing professional at Smile Architects, Pala.",
    testimonial: "I work in a client-facing role so visible braces were not an option for me. I didn't know lingual braces were available locally. Dr. Jeo is one of the few specialists with the training to place them and my experience was excellent.",
    published: true,
    featured: true,
    display_order: 3,
  },
  {
    title: "Thomas V. — Root Canal Treatment",
    story: "Single-visit root canal treatment at Smile Architects, Pala.",
    testimonial: "I was terrified of root canal treatment after everything I had heard. The reality was nothing like the horror stories. It was over in one visit and the tooth has been completely fine since. I genuinely had no pain during the procedure.",
    published: true,
    featured: false,
    display_order: 4,
  },
  {
    title: "Meera A. — Clear Aligners",
    story: "Clear aligner treatment at Smile Architects, Pala.",
    testimonial: "The aligners fitted perfectly and I could remove them for events. The results were clear after just a few months. The whole process was explained clearly at the start so I knew exactly what to expect.",
    published: true,
    featured: false,
    display_order: 5,
  },
  {
    title: "George P. — General Dentistry",
    story: "Long-term family patient at Smile Architects, Pala.",
    testimonial: "My family has been coming to Smile Architects for three years now. The clinic is clean and well-organised, the team is friendly and professional, and we've never had to wait long. It is exactly what a local dental clinic should be.",
    published: true,
    featured: false,
    display_order: 6,
  },
];

export const MIGRATE_FAQS = [
  {
    question: "Where is Smile Architects located?",
    answer: "Smile Architects is located on Kattakkayam Road, Pala, Kottayam, Kerala – 686575, near Federal Bank in Pala Town.",
    category: "General",
    published: true,
    display_order: 1,
  },
  {
    question: "What are the clinic's opening hours?",
    answer: "The clinic is open Monday to Saturday, 9:30 AM to 8:00 PM. The clinic is closed on Sundays.",
    category: "General",
    published: true,
    display_order: 2,
  },
  {
    question: "How do I book an appointment?",
    answer: "You can book an appointment by calling +91 9446 999 333, sending a WhatsApp message, or using the online appointment form on this website.",
    category: "General",
    published: true,
    display_order: 3,
  },
  {
    question: "Which dentists are available at Smile Architects?",
    answer: "Smile Architects is led by Dr. Jeo Tom Charls (MDS – Orthodontics and Dentofacial Orthopaedics), supported by Dr. Jintu Joan Jose and Dr. Ann Tresa T. Srambickal (both BDS – Aesthetic & General Dentistry), with Dr. Jom T. Kizhakkel (Periodontics & Implantology) and visiting consultants for oral surgery, paediatric dentistry and prosthodontics.",
    category: "General",
    published: true,
    display_order: 4,
  },
  {
    question: "Does the clinic offer parking?",
    answer: "Yes, ample car parking is available for patients visiting the clinic.",
    category: "General",
    published: true,
    display_order: 5,
  },
  {
    question: "Can I walk in without an appointment?",
    answer: "Walk-ins are welcome, though appointments are recommended to avoid waiting times. Call ahead to check availability.",
    category: "General",
    published: true,
    display_order: 6,
  },
  {
    question: "At what age should my child have an orthodontic assessment?",
    answer: "An initial orthodontic assessment from around age 7–9 is generally useful — this is when a mix of milk and permanent teeth allows the orthodontist to identify emerging bite issues. Early assessment does not always mean early treatment, but it allows appropriate monitoring and timely intervention if needed.",
    category: "Orthodontics",
    published: true,
    display_order: 7,
  },
  {
    question: "Do braces hurt?",
    answer: "Most patients experience some soreness and sensitivity for a few days after fitting and after each adjustment appointment. This is normal and is caused by the gentle pressure moving the teeth. Over-the-counter pain relief is usually sufficient. Discomfort typically settles within a few days.",
    category: "Orthodontics",
    published: true,
    display_order: 8,
  },
  {
    question: "How long will I need to wear braces?",
    answer: "Treatment duration varies from around 12 months for simple cases to 24–30 months for more complex situations. Your orthodontist will give an estimated duration after assessing your specific case.",
    category: "Orthodontics",
    published: true,
    display_order: 9,
  },
  {
    question: "Can adults have braces?",
    answer: "Yes. Adult orthodontic treatment is very common and can be just as effective as treatment in younger patients, provided teeth and gums are healthy. All appliance types — including more discreet options like ceramic braces, lingual braces or clear aligners — are available.",
    category: "Orthodontics",
    published: true,
    display_order: 10,
  },
  {
    question: "What happens if I don't wear my retainer after treatment?",
    answer: "Teeth have a natural tendency to drift back towards their original positions. Without consistent retainer wear, this relapse can occur — sometimes within months. Retainers are prescribed as part of every orthodontic treatment. Full-time wear is usually required initially, transitioning to night-time wear long-term.",
    category: "Orthodontics",
    published: true,
    display_order: 11,
  },
];

export const MIGRATE_SITE_SETTINGS = {
  key: "clinic_info",
  value: {
    name: "Smile Architects",
    tagline: "Multispeciality Dental Clinic & Advanced Orthodontic Centre",
    phone: "+919446999333",
    email: "drjeosmilearchitects@gmail.com",
    address: "Kattakkayam Road, Pala, Kottayam, Kerala – 686575",
    whatsapp: "https://wa.me/919446999333",
    facebook: "",
    instagram: "",
    hours_weekdays: "Monday – Saturday: 9:30 AM – 8:00 PM",
    hours_sunday: "Sunday: Closed",
    google_maps_embed: "https://maps.google.com/maps?q=Smile+Architects+Pala+Kottayam+Kerala&output=embed",
    google_maps_directions: "https://maps.google.com/?q=Smile+Architects,+Kattakkayam+Road,+Pala,+Kottayam,+Kerala+686575",
  },
};
